version: "3.3"

services:
  database:
    image: postgres
    container_name: invest-advisor-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 42
      POSTGRES_DB: investadvisor
    ports:
      - "5433:5432"

  backend:
    build: ./
    container_name: invest-advisor-app
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://invest-advisor-db:5432/investadvisor
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 42
    depends_on:
      - database
    ports:
      - "8080:8080"
    entrypoint: ["java", "-Dapp.home=/usr/src/invest-advisor/home", "-jar", "/usr/local/invest-advisor/invest-advisor.jar"]
