server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    ROOT: INFO
    org.springframework: INFO

spring:
  application:
    name: invest-advisor
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/investadvisor
    username: postgres
    password: 1
  liquibase:
    enabled: false
    change-log: "classpath:db/changelog/db.changelog-master.yaml"

springdoc:
  swagger-ui:
    path: '/swagger-ui'
    operations-sorter: method
    doc-expansion: none
    disable-swagger-default-url: true

variables:
  twelvedataApiKey: 997ed3a430e644949befeab17b59d302
  portfolioMonitorTrigger: 75
  portfolioMonitorCron: "@hourly"